### ISSUE TITLE
Podpięcie Swaggera

### ISSUE THREAD

**Issue by jkkostrzewski** [jkkostrzewski/zzpj-project#15]
Na prezentacji projektu 20 maja dostaliśmy informację, że nie musimy właściwie żadnego frontu robić. Podpinamy Swaggera i szykujemy kolekcję w Postmanie do prezentacji końcowej.

**Comment by jkkostrzewski** [comment]
Swagger jest teraz na masterze. Potrzebujemy dodać brakujące adnotacje wraz z uzupełnianiem API.

**Comment by paluszkiewiczB** [comment]
Trzeba dopisać: w endpoincie do pobierania wszystkich sklepów, jeśli chcesz posortować wg zagnieżdżonej wartości (np. pole wewnątrz ShopDetails, które jest polem w Shop), trzeba podać nazwę pola, potem po podłodze pola zagnieżdżonego
shopDetails_name

Do weryfikacji

**Comment by jkkostrzewski** [comment]
Każdy kontroler ma dodane adnotacje. Zamykam.
