### ISSUE TITLE
Ustawienie złej wartości filtra stockType przy wyszukiwaniu sklepów powoduje zwrócenie response'a z wyjątkiem

### ISSUE THREAD

**Issue by jkkostrzewski** [jkkostrzewski/zzpj-project#26]
Jak reprodukować:
- Wprowadź dowolną wartość dla stockType inną niż ta z listy enumów

Wynik:
![image](https://user-images.githubusercontent.com/45603875/84597969-a74e1c00-ae67-11ea-8e89-b841151c8e51.png)

Taki sam błąd występuje dla isOpen kiedy wpiszemy wartość "trues":
![image](https://user-images.githubusercontent.com/45603875/84597987-c8167180-ae67-11ea-8bde-3cc879d68123.png)

**Comment by jkkostrzewski** [comment]
Wprowadzenie stringa dla maxCapacity i maxQueueLength daje takie same efekty:
![image](https://user-images.githubusercontent.com/45603875/84598009-fdbb5a80-ae67-11ea-88b5-2d448c0d06c3.png)

**Comment by sebastianKazmierski** [comment]
robimy ogolny handler na wszstko typu     @ExceptionHandler(ConversionFailedException.class) czy każdy rzuca swoj wyjatek i robi sobie własną obsługę? bo ja tez potrzebuje konwersji ze stringa na enuma

**Comment by paluszkiewiczB** [comment]
IMO trzeba to ogarnąć globalnie, tak żeby odpowiedzi przy błędach na konwersji i wszystkich wyjątkach rzucanych przez Bean Validation były takie same np.
```
rejectedValues: [
   { 
      "name": "isOpen"
      "type": "boolean"
      "rejectedValue": "trues"
   },
   { 
      "name": "type"
      "type": "StockType"
      "rejectedValue": "dziabadziabadziaba"
   }
]
```

**Comment by jkkostrzewski** [comment]
Bug został naprawiony.
