### ISSUE TITLE
API do odczytywania istniejacych sklepow

### ISSUE THREAD

**Issue by paluszkiewiczB** [jkkostrzewski/zzpj-project#9]
-  filtrowanie według statystyk i właności
 - sortowanie wg:
   - odległości do sklepu (do tego trzeba bedzie zatrudnić kontroler)
   - czasu oczekiwania (na razie jakiś random albo hardcodowane, trzeba zebrac najpierw statystyki na podstawie ktorych bedzie mozna aproksymowac tę wartość)
   - wielkości sklepu 
   - odległości + czasie oczekiwania (podróż + kolejka) -> też mock

**Comment by jkkostrzewski** [comment]
czas oczekiwania - może jakaś opcja ankiety dla użytkownika?

**Comment by paluszkiewiczB** [comment]
Musielibyśmy liczyć na to, że każdy po zakupach będzie klikał ile był.
Ale nie wiem jak to inaczej zrobić

**Comment by jkkostrzewski** [comment]
Nie musielibyśmy imo - i tak to będzie tylko szacowany czas
